spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proj-test-2
    username: root
    password: Iopjkl@890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:

      ddl-auto: update
    show-sql: true

    database-platform: org.hibernate.dialect.MySQLDialect
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: abhishekpanda890@gmail.com
    password: onqdiftphczjuijy
    protocol: smtp
    tls:
      trust-all: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true  
    
server:
  port: 7040   